### PR TITLE
Add formatting to text output

### PR DESCRIPTION
**Pull request by ArselMuginov**
I saw changes in package branch, but thought it can be done simpler.
Open to changes!

### CODE REVIEW

**Comment by xenova** [comment]
Wow this is great! 😄 

I was really unsure what the best way to do this would be. I'll share some of my thoughts here:

1. It needs to be simple enough for most users
2. It must be able to support complex features (for advanced users)
3. It must be highly customizable
4. It must be scalable (in future, minimal changes should need to be made for it to work if new things are added)

You mentioned that you saw what I started with in the `package` branch (I assume you saw these files: https://github.com/xenova/chat-replay-downloader/tree/package/chat_replay_downloader/formatting)

The idea behind it is to create a JSON file with custom formats and then use a "name" as a command line argument (e.g. `--format "default"`). Admittedly, it looks quite complicated... but I did not know of a better way to allow for more complex features. Let me explain. 

First, we start off with a template string: `{time_text|timestamp}{author_badges}{amount}{author_display_name|author_name}: {message}`. This will actually work already, but most users want more options, so they can specify that with the keys. The `|` between keys just symbolizes that additional/fallback values can be specified in the case where some key does not exist. 

Part of the formatting file:
```json
"time_text": {
    "prefix": "[",
    "suffix": "] "
},
"timestamp": {
    "prefix": "[",
    "format": "%Y-%m-%d %H:%M:%S",
    "suffix": "] ",
},
"author_badges": {
    "prefix": "(",
    "separator": ", ",
    "suffix": ") "
}
```
This allows for a prefix, suffix and additional formatting to be supplied - BUT (importantly) will not show if the key (e.g. `author_badges`) is absent from the message. This was required since - say for example there are no badges, then some messages would be like:

```
[2020-12-16 20:34:01] (2-Month Subscriber, Prime Gaming) Courtney_twing: He was going to kill you next
[2020-12-16 20:34:03] () K3oth: aight sleepy goodbye
[2020-12-16 20:34:07] () helenakova: i dont think its train bcs he acts normal, crewlike(?)
[2020-12-16 20:34:08] () losedorerd: Aipha is lyinggg
[2020-12-16 20:34:12] (1-Month Subscriber) shaniaaa777: 5upL 5upL 5upL 5upL 5upL 5upL
[2020-12-16 20:34:12] (Moderator, 3-Month Subscriber, Verified) Fossabot: 5upL 5upL 5upL 5upL
[2020-12-16 20:34:14] (2-Month Subscriber, 10 Gift Subs) duhhsaurus: @whydolhearbossmusic misery loves company 5upL riooLove
```

The proposed system fixes this to be:

```
[2020-12-16 20:34:01] (2-Month Subscriber, Prime Gaming) Courtney_twing: He was going to kill you next
[2020-12-16 20:34:03] K3oth: aight sleepy goodbye
[2020-12-16 20:34:07] helenakova: i dont think its train bcs he acts normal, crewlike(?)
[2020-12-16 20:34:08] losedorerd: Aipha is lyinggg
[2020-12-16 20:34:12] (1-Month Subscriber) shaniaaa777: 5upL 5upL 5upL 5upL 5upL 5upL
[2020-12-16 20:34:12] (Moderator, 3-Month Subscriber, Verified) Fossabot: 5upL 5upL 5upL 5upL
[2020-12-16 20:34:14] (2-Month Subscriber, 10 Gift Subs) duhhsaurus: @whydolhearbossmusic misery loves company 5upL riooLove
```

Lastly, I added `matching` criteria. This means that a different format will be applied for different messages. For some messages (like bans, subscriptions, memberships, etc.), a user might want a different output to be shown (see the JSON in the folder above). As an example, for Twitch, a user can specify the output for ban messages:
```
[2020-12-16 20:42:00] (Broadcaster) Xenova: test message
[2020-12-16 20:42:09] test was permanently banned.
[2020-12-16 20:42:19] test was timed out for 100 seconds.
```

However, the current system would show:
```
[2020-12-16 20:44:52] (Broadcaster) Xenova: test message
[2020-12-16 20:44:55] : 
[2020-12-16 20:45:05] : 
```
since ban messages do not have messages:

```json
[
    {
        "action_type": "text_message",
        "author_badges": [
            {
                "badge_id": "5527c58c-fb7d-422d-b71b-f309dcb85cc1",
                "click_action": "none",
                "click_url": "",
                "description": "Broadcaster",
                "icons": [
                    {
                        "height": 18,
                        "id": "18x18",
                        "url": "https://static-cdn.jtvnw.net/badges/v1/5527c58c-fb7d-422d-b71b-f309dcb85cc1/1",
                        "width": 18
                    },
                    {
                        "height": 36,
                        "id": "36x36",
                        "url": "https://static-cdn.jtvnw.net/badges/v1/5527c58c-fb7d-422d-b71b-f309dcb85cc1/2",
                        "width": 36
                    },
                    {
                        "height": 72,
                        "id": "72x72",
                        "width": 72
                    }
                ],
                "image_url_4x": "https://static-cdn.jtvnw.net/badges/v1/5527c58c-fb7d-422d-b71b-f309dcb85cc1/3",
                "title": "Broadcaster",
                "type": "broadcaster",
                "version": 1
            }
        ],
        "author_display_name": "Xenova",
        "author_id": "86982947",
        "author_name": "xenova",
        "channel_id": "86982947",
        "colour": "#FF69B4",
        "is_moderator": false,
        "message": "test message",
        "message_id": "6d9d90a0-1a72-4e2a-b183-d7256d53934e",
        "message_type": "text_message",
        "timestamp": 1608144292347000
    }, 
    {
        "action_type": "clear_chat",
        "ban_type": "permanent",
        "banned_user": "test",
        "channel_id": "86982947",
        "message_type": "ban_user",
        "timestamp": 1608144295883000
    }, 
    {
        "action_type": "clear_chat",
        "ban_duration": 100,
        "ban_type": "timeout",
        "banned_user": "test",
        "channel_id": "86982947",
        "message_type": "ban_user",
        "timestamp": 1608144305641000
    }
]
```

Perhaps I can pose the following question:
With the system you implemented, is it possible to allow for:

1. Fallback options
2. Conditional formatting (i.e. prefix/suffix not added if not present)
3. Different formatting for different message types

Thanks for the pull request though! I really appreciate it. Would love to hear your opinion on all of this too.

**Comment by ArselMuginov** [comment]
Thank you for detailed answer 😄 

Firstly, answering the questions:
1. Fallback options generally are not implemented, only coded stuff like time_text/timestamp. If we to add a new service it would not work so it needs to be general, yes
2. Conditional formatting is implemented in a way that there are several templates customizable: main one and for each part. So enclosing brackets and such will not be shown if message to be formatted does not have this part, e.g. `${badges}...` & `[{}]`, where `{}` are to be replaced with `str.format()`, and whole `${badges}` prints like empty string is not present
3. This part is not supported, because I don't know about message types so much

So, my questions:
1. Are prefix and suffix necessary? It can be simplified as enclosing characters with something representing actual content, like empty curly braces
2. Can we standardize datetimes we get from website? I worked only with YouTube and noticed sometimes it's `time_text`, sometimes `timestamp`. So can we say that there are two types of datetime, one counting from start of stream and other from some epoch or are there some other variants?
3. I didn't found a good way to pass a dictionary through argparse, so if we add other parts/values to format, I don't know a good way to keep using what I've done in this PR: to add each argument for each part. JSON seems to be good here.
4. Also, how much can I base my work on package branch? Are changes there somewhat set in stone?

Raw regex is hard to maintain, but it can be hard to work only with stuff like `str.format()` or `string.Template`, I would say I don't have enough experience to say definitely.

I would say using JSON and selecting profiles is good if user found consistent needed way of formatting.

It would be nice to make some sort of an API in its own file, what fields, message types and so on program can process, I think it would add to understanding. Maybe if you have some text about it I can try to standardize it, try 😄 

If we agree on how formatting needs to be done I think we can combine your formatting and mine, make it more general, add JSON support like in your implementation. What do you think?

**Comment by xenova** [comment]
> 1. Fallback options generally are not implemented, only coded stuff like time_text/timestamp. If we to add a new service it would not work so it needs to be general, yes

👍 

> 2. Conditional formatting is implemented in a way that there are several templates customizable: main one and for each part. 

So enclosing brackets and such will not be shown if message to be formatted does not have this part, e.g. `${badges}...` & `[{}]`, where `{}` are to be replaced with `str.format()`, and whole `${badges}` prints like empty string is not present

I do like the simplicity of your solution though - allowing for command line arguments to be passed in to control the formatting. The only issue with this is that it is very specific (e.g. you must predefine a certain number of arguments for a certain number of keys). Adding support for something else, such as badges, would not be very simple. A possible solution could be to add variable arguments of the form `--format-[key] [format]` which would allow for any key to be formatted without needing to specify it in advance. For example: `... --format-timestamp hh:mm:ss ...`. One issue with this is it would result in really long, commands when a more advanced format is desired.

> 3. This part is not supported, because I don't know about message types so much

This is a new addition to the `package` branch. It was necessary because YouTube may handle different message types differently: `text_message` vs. `paid_message` vs. `sticker`, etc. Some have keys which others don't. Users may also only want to get some types of messages (e.g. #7, #38). This is done through the `--message_types` or `--message_groups` command line arguments. Similar tools do not allow for this, so it would be great to have this as a feature. YouTube has many different types of messages:
```
    _MESSAGE_GROUPS = {
        # 'group_name':[
        #     'message_types'
        # ]
        'messages': [
            'text_message'  # normal message
        ],
        'superchat': [
            # superchat messages which appear in chat
            'membership_item',
            'paid_message',
            'paid_sticker',
        ],
        'tickers': [
            # superchat messages which appear ticker (at the top)
            'ticker_paid_sticker_item',
            'ticker_paid_message_item',
            'ticker_sponsor_item',
        ],
        'banners': [
            'banner',
            'banner_header'
        ],
        'donations': [
            'donation_announcement'
        ],
        'engagement': [
            # message saying live chat replay is on
            'viewer_engagement_message',
        ],
        'purchases': [
            'purchased_product_message'  # product purchased
        ],
        'mode_changes': [
            'mode_change_message'  # e.g. slow mode enabled
        ],
        'deleted': [
            'deleted_message'  # old: 'deleted_state_message'
        ],
        'placeholder': [
            'placeholder_item'  # placeholder
        ]
    }
```
Twitch also has a lot (too many to list here, but you can check the code)

> So, my questions:
> 
> 1. Are prefix and suffix necessary? It can be simplified as enclosing characters with something representing actual content, like empty curly braces

I initially had something similar to this, but I found it was very confusing when specifying a template. e.g. `{time_text|timestamp}{author_badges}{amount}{author_display_name|author_name}: {message}` vs. `{[{time_text|timestamp}] }{({author_badges}) }{*{amount}* }{{author_display_name|author_name}}: {{message}}`. Note that the external curly braces are necessary to indicate what should or should not be shown depending on whether the key exists in the item. The proposed solution could work if each key format was specified in advance (as you have tried with `--timestamp-format`, `--badges-format`, etc.). However, as discussed above, this list may not be able to be defined in advance. I should also mention that I believe a "template" is necessary in case the user wishes to specify symbols which should always be present in the message, regardless of whether it contains a key or not. For example, `:` and spaces.

> 2. Can we standardize datetimes we get from website? I worked only with YouTube and noticed sometimes it's `time_text`, sometimes `timestamp`. So can we say that there are two types of datetime, one counting from start of stream and other from some epoch or are there some other variants?

So, YouTube (and Twitch) always return epoch/unix time (this is standard). The problem comes when the video is a replay or live. replays have timestamps, while live videos do not. One may think it is simple to calculate the offset, but unfortunately it is not possible (to my knowledge) to obtain stream-start-time at microsecond precision without authenticated API requests - as I have stated before, I wish to keep this tool authentication-free so that anyone can use it without signing up for an API key. I have discussed this problem further in #20 (re: offset errors, etc.).

> 3. I didn't found a good way to pass a dictionary through argparse, so if we add other parts/values to format, I don't know a good way to keep using what I've done in this PR: to add each argument for each part. JSON seems to be good here.

I agree that JSON is probably the way forward - I have seen similar tools use this technique, which was another reason for trying it here. There are a few ways to pass custom/variable arguments to argparse (as described above), so we could investigate that further to provide an alternative method for specifying formats. However, I believe that, if we simply come up with an extensive list of predefined formats (e.g. 24 hour time, with badges, without badges, etc.), most users will be comfortable with simply passing a `--format [name]` argument to the program. Advanced users can perhaps create their own json file and pass it in with `--format_file [file]` to allow for them to select custom formats.

> 4. Also, how much can I base my work on package branch? Are changes there somewhat set in stone?

I've spent the past 2-ish weeks on it, and I think most of it is ready for use (at least most things should be relatively finalized). This of course does not mean anything is "set in stone" per say... suggestions/changes are always welcome! There are just things (like the formatting) which need some work before merging it with the `master` branch.

> Raw regex is hard to maintain, but it can be hard to work only with stuff like `str.format()` or `string.Template`, I would say I don't have enough experience to say definitely.

I have decent experience with regex, so I think we can make it work. I am by no means an expert (I'm sure there are many optimisations to be made), but I think that it will be sufficient for our use-case.

> I would say using JSON and selecting profiles is good if user found consistent needed way of formatting.

I agree, especially if we define a lot of formats for basic users. Advanced users can specify their own formats (as mentioned above).

> It would be nice to make some sort of an API in its own file, what fields, message types and so on program can process, I think it would add to understanding. Maybe if you have some text about it I can try to standardize it, try 😄

I 100% agree. This is definitely an important thing before releasing - documentation. I will try my best to do that while I write the code, but we can always make a section in the wiki/readme dedicated to it.

> If we agree on how formatting needs to be done I think we can combine your formatting and mine, make it more general, add JSON support like in your implementation. What do you think?

That would be great! I feel like their can be a good combination of command line arguments and JSON support. How would you suggest we change/improve the "current" (what is currently in the `package` [branch](https://github.com/xenova/chat-replay-downloader/blob/package/chat_replay_downloader/formatting/format.py)) system? To be quite honest, I don't really like some of the hard-coding, but unfortunately it is necessary for some things (e.g. joining the list of badges, or specifying a format for the timestamp). Looking forward to hearing your response! 👍

**Comment by ArselMuginov** [comment]
> I initially had something similar to this, but I found it was very confusing when specifying a template. e.g. {time_text|timestamp}{author_badges}{amount}{author_display_name|author_name}: {message} vs. {[{time_text|timestamp}] }{({author_badges}) }{*{amount}* }{{author_display_name|author_name}}: {{message}}. 

Same! I inherited `Template` class and made changes, and then thought it is very confusing, so didn't continue.

I propose instead of prefix and suffix do:
```python
#...main template...
"Badges": "({}) ",
```
Or is it confusing too?

I think we use `--format` for profile and if user needs momentary changes he adds one of other switches, so not format but `--template`? And if needed `--author-template`? Not sure about list separator/delimiter, maybe like `--badges-delim-template`, but it gets long, maybe JSON only. Creating argparse arguments with loop is a good idea!

Do we need formatting of `time_text`? Are there many forms? I saw `00:00` and `00:00:00`.

So in terms of code that parses template I think it can be simplified. Main template is a `string.Template` class or `str` and using `.format()`. `Template` provides a little bit more customization and I assume more for user input. Nothing hurts to just do `{author}: {message}` with `str.format()` though.

Identifiers in main template are checked with JSON/cli args to substitute. If we use `smth{}smth` we could `.format()` it so it looks simple. Duplicating braces if escaping is needed is not so bad I think. Check for empty of course.

And there would be types of formatting parts, like time is unique, simple ones are substitution with enclosing characters, list type for delimiter, something else? `delim.join(badges)` is good for list types, I think, and then enclosing characters.
 
I think fallbacks can be inside smaller part, like `{author}` in main template and in `"author"` in JSON list the fallbacks?

I'm not at my computer, I hope it's understandable.

**Comment by xenova** [comment]
> I propose instead of prefix and suffix do:
> 
> ```python
> #...main template...
> "Badges": "({}) ",
> ```

Okay, I like this idea 👍 This also allows users to completely replace the value with text. (Useful for certain message types). By not specifying a `{}`, the value will not be displayed. What about this:

**Current version:**
```python
"default": {
	"template": "{time_text|timestamp}{author_badges}{amount}{author_display_name|author_name}: {message}",
	"keys": {  # We could potentially remove this and just have the keys (e.g. time_text, timestamp) on the same level (there should not be any template key soon)
		"time_text": {
			"prefix": "[",
			"suffix": "] "
		},
		"timestamp": {
			"prefix": "[",
			"format": "%Y-%m-%d %H:%M:%S",
			"suffix": "] "
		},
		"author_badges": {
			"prefix": "(",
			"separator": ", ",
			"suffix": ") "
		},
		"amount": {
			"prefix": "*",
			"suffix": "* "
		}
	}
}
```

**Proposed version:**
```python
"default": {
	"template": "{time_text|timestamp}{author_badges}{amount}{author_display_name|author_name}: {message}",
        "matching": ["message_type_1", "message_type_2"],
	"keys": {  
	        "time_text": "[{}] ",
	        "timestamp": {
		        "value": "[{}] ",
		        "format": "%Y-%m-%d %H:%M:%S"
	        },
	        "author_badges": {
		        "value": "({}) ",
		        "separator": ", "
	        },
	        "amount": "*{}* "
         }
}
```

Some benefits about this (which combine both our solutions):
- Simpler prefix/suffix specification
- Users can specify either a value (e.g. "time_text": "[{}] ") alone, or, if they want to add extra options, can add it to a dictionary with other options (as well as how the value will be replaced) - e.g. timestamp.
- Users can override basic formats with command line arguments (e.g. `--timestamp-format hh:mm:ss`). If they want more advanced features, they can modify the JSON file or create their own file which can be specified with `--format_file x.json`.
- Users can easily specify the order and inclusion of keys using, a `--format` command line argument (e.g.  `--format "{author}: {message}"` )
- Advanced users can read the documentation further for specifying "matching message types"
- The template string defines text that will always display and allows for specifying fallback options

> I think we use `--format` for profile and if user needs momentary changes he adds one of other switches, so not format but `--template`? And if needed `--author-template`? Not sure about list separator/delimiter, maybe like `--badges-delim-template`, but it gets long, maybe JSON only. Creating argparse arguments with loop is a good idea!

I think for things like that, JSON would be fine. But we could always allow users to specify command line arguments to override parts of the JSON format. I like that idea 👍 

> Do we need formatting of `time_text`? Are there many forms? I saw `00:00` and `00:00:00`.

I think it is quite standard how time texts appear. These values are (for the most part) generated by the websites. With this format, there are no leading zeroes, except for when it is less than a minute. e.g. 0:32, 5:47, 10:12, 58:40, 1:11:07. We could allow for other formats, but that's not a big priority now.

> So in terms of code that parses template I think it can be simplified. Main template is a `string.Template` class or `str` and using `.format()`. `Template` provides a little bit more customization and I assume more for user input. Nothing hurts to just do `{author}: {message}` with `str.format()` though.

We could perhaps use this, but the only problem I found is with the fallback options (e.g. `{author_display_name|author_name}: {message}`). `str.format()` does not support this, so I think we have to use regex. Luckily I've already implemented this, so it should be fine. raw curly braces can be escaped using `\` (but we can make this anything really, like another curly brace)

> Identifiers in main template are checked with JSON/cli args to substitute. If we use `smth{}smth` we could `.format()` it so it looks simple. Duplicating braces if escaping is needed is not so bad I think. Check for empty of course.

Agreed 👍 That would be great for when we have to do replacements like that. `.format` actually allows for empty strings and strings without formats to be specified:
```
>>> a = 'test'
>>> a.format(1)
'test'
>>> a = ''      
>>> a.format(1)
''
```
So, that should be quite simple to implement.

> And there would be types of formatting parts, like time is unique, simple ones are substitution with enclosing characters, list type for delimiter, something else? `delim.join(badges)` is good for list types, I think, and then enclosing characters.

Yes I think that should be fine. Some things I had to figure out for the tool was how to "standardize" it across different sites (YouTube/Twitch), so some things, like badges, look like:

Twitch:
```json
"author_badges": [
            {
                "badge_id": "5d9f2208-5dd8-11e7-8513-2ff4adfae661",
                "click_action": "subscribe_to_channel",
                "click_url": "",
                "description": "1-Month Subscriber",
                "icons": [
                    {
                        "height": 18,
                        "id": "18x18",
                        "url": "https://static-cdn.jtvnw.net/badges/v1/5d9f2208-5dd8-11e7-8513-2ff4adfae661/1",
                        "width": 18
                    },
                    {
                        "height": 36,
                        "id": "36x36",
                        "url": "https://static-cdn.jtvnw.net/badges/v1/5d9f2208-5dd8-11e7-8513-2ff4adfae661/2",
                        "width": 36
                    },
                    {
                        "height": 72,
                        "id": "72x72",
                        "url": "https://static-cdn.jtvnw.net/badges/v1/5d9f2208-5dd8-11e7-8513-2ff4adfae661/3",
                        "width": 72
                    }
                ],
                "months": 1,
                "title": "1-Month Subscriber",
                "type": "subscriber",
                "version": 0
            },
            {
                "badge_id": "bbbe0db0-a598-423e-86d0-f9fb98ca1933",
                "click_action": "visit_url",
                "click_url": "https://gaming.amazon.com",
                "description": "Prime Gaming",
                "icons": [
                    {
                        "height": 18,
                        "id": "18x18",
                        "url": "https://static-cdn.jtvnw.net/badges/v1/bbbe0db0-a598-423e-86d0-f9fb98ca1933/1",
                        "width": 18
                    },
                    {
                        "height": 36,
                        "id": "36x36",
                        "url": "https://static-cdn.jtvnw.net/badges/v1/bbbe0db0-a598-423e-86d0-f9fb98ca1933/2",
                        "width": 36
                    },
                    {
                        "height": 72,
                        "id": "72x72",
                        "url": "https://static-cdn.jtvnw.net/badges/v1/bbbe0db0-a598-423e-86d0-f9fb98ca1933/3",
                        "width": 72
                    }
                ],
                "title": "Prime Gaming",
                "type": "premium",
                "version": 1
            }
        ]
```

YouTube:
```json
"author_badges": [
            {
                "icons": [
                    {
                        "height": 16,
                        "id": "16x16",
                        "url": "https://yt3.ggpht.com/L2rcnSue6FkX2v0YQH1Olir09Cc6g0FwNTCHwa-4bT3hlO843pTF42Cmw03QLGS7fKYvufTF=s16-c-k",
                        "width": 16
                    },
                    {
                        "height": 32,
                        "id": "32x32",
                        "url": "https://yt3.ggpht.com/L2rcnSue6FkX2v0YQH1Olir09Cc6g0FwNTCHwa-4bT3hlO843pTF42Cmw03QLGS7fKYvufTF=s32-c-k",
                        "width": 32
                    },
                    {
                        "id": "source",
                        "url": "https://yt3.ggpht.com/L2rcnSue6FkX2v0YQH1Olir09Cc6g0FwNTCHwa-4bT3hlO843pTF42Cmw03QLGS7fKYvufTF"
                    }
                ],
                "title": "New member"
            }
        ]
```

> I think fallbacks can be inside smaller part, like `{author}` in main template and in `"author"` in JSON list the fallbacks?

I thought of this initially, but I think there could be strange circular/infinite loops that could occur if two keys specify each other as fallbacks. I think the `{key_1|key_2}` is simple enough

**Comment by ArselMuginov** [comment]
All right I agree, we already have regex for fallbacks working so we use it, new JSON is nice too.

So how do we do this? I think close this one and add code to package branch? I can add some code if needed, like argparse arguments.

**Comment by xenova** [comment]
Okay that sounds good! :) Hopefully the existing code in the `package` branch will be a good starting point. Most of it is probably not the best, so I welcome any changes haha. I tried to make some comments, but it is not very well documented 😅. 

I used `re.sub` to perform substitution on the matches. Luckily, you can pass a function into `re.sub` to return a string based on the input. I think this could be useful:
`substitution = re.sub(self._INDEX_REGEX, lambda result: self.replace(result, item, keys), template)`


I will continue working on the actual content extraction from the sites.

**Comment by xenova** [comment]
Hi @ArselMuginov, have you by any change made any progress on it? 😃

**Comment by ArselMuginov** [comment]
Oh sorry I misunderstood. I wasn't doing it. I got scared by that regex method 😄 and thought maybe providing ideas will be enough. I can try to do some stuff we were discussing. 😅

**Comment by xenova** [comment]
No worries! 😄 ... I've been quite busy adding support for new sites and improving core functionality. So, if you had time, it would be greatly appreciated! 🔥

**Pull request closed without merging**
